# Generated by Django 4.2 on 2023-05-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activecode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('isactive', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'activecode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Closetypecode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('closetype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'closetypecode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Educationlevelcode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('education', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'educationlevelcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experiencelevelcode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('experience', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'experiencelevelcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobcode',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.BigIntegerField()),
                ('keyword', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'jobcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobsearch',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('active', models.BigIntegerField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('company_detail_href', models.TextField(blank=True, null=True)),
                ('company_detail_name', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('location_code', models.TextField(blank=True, null=True)),
                ('location_name', models.TextField(blank=True, null=True)),
                ('jobtype_code', models.TextField(blank=True, null=True)),
                ('jobtype_name', models.TextField(blank=True, null=True)),
                ('keyword_code', models.TextField(blank=True, null=True)),
                ('keyword_name', models.TextField(blank=True, null=True)),
                ('experiencelevel_code', models.BigIntegerField(blank=True, null=True)),
                ('experiencelevel_min', models.BigIntegerField(blank=True, null=True)),
                ('experiencelevel_max', models.BigIntegerField(blank=True, null=True)),
                ('experiencelevel_name', models.TextField(blank=True, null=True)),
                ('educationlevel_code', models.TextField(blank=True, null=True)),
                ('educationlevel_name', models.TextField(blank=True, null=True)),
                ('salary_code', models.TextField(blank=True, null=True)),
                ('salary_name', models.TextField(blank=True, null=True)),
                ('closetype_code', models.TextField(blank=True, null=True)),
                ('closetype_name', models.TextField(blank=True, null=True)),
                ('posting_date', models.TextField(blank=True, null=True)),
                ('modification_timestamp', models.TextField(blank=True, null=True)),
                ('opening_timestamp', models.TextField(blank=True, null=True)),
                ('expiration_timestamp', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobsearch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobtypecode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'jobtypecode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locationcode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'locationcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salarycode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('salary', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'salarycode',
                'managed': False,
            },
        ),
    ]
