# Generated by Django 4.2 on 2023-05-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20, null=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('career', models.CharField(max_length=10, null=True)),
                ('education', models.CharField(max_length=20, null=True)),
                ('work_type', models.CharField(max_length=10, null=True)),
                ('skills', models.ManyToManyField(to='main.skill')),
            ],
        ),
    ]
