# Generated by Django 4.2 on 2023-05-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill_parameter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
